<template>
  <div class="shared-page-container" v-if="recording">
    <!-- Read Only Header for Shared View -->
    <header class="shared-header no-print">
      <div class="brand-row">
        <div class="shared-logo-icon">
          <Sparkles size="16" color="#FFFFFF" stroke-width="2.5" />
        </div>
        <span class="brand-title">ClarifAi Shared Intelligence</span>
      </div>

      <h1 class="page-title">{{ recording.title }}</h1>
      
      <div class="meta-pills-row">
        <span class="meta-pill">
          <Calendar size="13" />
          <span>{{ formattedDate }}</span>
        </span>
        <span class="meta-pill" v-if="recording.duration">
          <Clock size="13" />
          <span class="font-tabular">{{ formattedDuration }}</span>
        </span>
        <span class="meta-pill medical-pill" v-if="recording.is_medical">
          <Stethoscope size="13" />
          <span>Clinical Consultation</span>
        </span>
        <span class="meta-pill pill-shared">
          <span>Read-Only Preview</span>
        </span>
      </div>

      <div class="shared-actions-bar">
        <button class="apple-btn-secondary" @click="copySummary" v-if="recording.summary_md">
          <Check size="14" v-if="copied" class="text-green" />
          <Copy size="14" v-else />
          <span>{{ copied ? 'Copied!' : 'Copy Summary' }}</span>
        </button>

        <button class="apple-btn-secondary" @click="printSummary" v-if="recording.summary_md">
          <Printer size="14" />
          <span>Print / Save PDF</span>
        </button>
      </div>
    </header>

    <!-- Summary Document Card -->
    <main class="shared-doc-wrapper">
      <div class="apple-doc-card" v-if="recording.summary_md">
        <div class="doc-header screen-summary-header">
          <div class="flex items-center gap-2">
            <div class="doc-icon-badge" :class="{ 'medical-icon-badge': recording.is_medical }">
              <Stethoscope v-if="recording.is_medical" size="18" class="text-emerald-600" />
              <Sparkles v-else size="18" color="#0071E3" />
            </div>
            <div>
              <h2 class="doc-heading">{{ recording.is_medical ? 'Clinical SOAP Note' : 'Executive Summary' }}</h2>
              <span class="doc-subheading">{{ recording.is_medical ? 'Structured Clinical Consultation Summary' : 'Generated by ClarifAi Local LLM' }}</span>
            </div>
          </div>
        </div>
        <div class="markdown-content" v-html="parsedSummary"></div>
      </div>
      
      <div v-else class="apple-doc-card empty-card">
        <p>No executive summary generated yet for this recording.</p>
      </div>
    </main>
  </div>

  <!-- Error State -->
  <div v-else-if="loadError" class="full-page-loader">
    <div class="apple-doc-card text-center max-w-md p-8" style="max-width: 440px; margin: 0 1rem; text-align: center;">
      <h3 style="font-size: 1.2rem; font-weight: 700; color: #E03131; margin-bottom: 0.5rem;">Access Error</h3>
      <p style="font-size: 0.9rem; color: var(--text-secondary); margin-bottom: 1.5rem;">
        {{ loadError }}
      </p>
      <button class="apple-primary-btn" @click="fetchRecording" style="margin: 0 auto;">
        Try Again
      </button>
    </div>
  </div>

  <!-- Loading State -->
  <div v-else class="full-page-loader">
    <Loader2 class="animate-spin text-blue" size="44" />
    <span class="loader-label">Loading shared insight...</span>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useRoute } from 'vue-router'
import axios from 'axios'
import moment from 'moment'
import { marked } from 'marked'
import { useToast } from 'primevue/usetoast'
import { Calendar, Clock, Sparkles, Loader2, Printer, Copy, Check, Stethoscope } from '@lucide/vue'
import { useTitle } from '@vueuse/core'

const route = useRoute()
const toast = useToast()
const recording = ref(null)
const loadError = ref(null)
const copied = ref(false)

const title = computed(() => recording.value ? `${recording.value.title} — ClarifAi (Shared)` : 'ClarifAi Shared Insight')
useTitle(title)

const fetchRecording = async () => {
  loadError.value = null
  try {
    const res = await axios.get(`/api/recordings/share/${route.params.id}`)
    recording.value = res.data
  } catch (e) {
    console.error("Failed to load recording", e)
    loadError.value = e.response?.data?.detail || 'Recording not found or is private.'
    toast.add({ severity: 'error', summary: 'Access Error', detail: 'Recording not found or is private.', life: 5000 })
  }
}

onMounted(() => {
  fetchRecording()
})

const parsedSummary = computed(() => {
  return recording.value?.summary_md ? marked(recording.value.summary_md) : ''
})

const copySummary = () => {
  if (!recording.value?.summary_md) return
  navigator.clipboard.writeText(recording.value.summary_md)
  copied.value = true
  toast.add({ severity: 'success', summary: 'Copied', detail: 'Summary copied to clipboard.', life: 2500 })
  setTimeout(() => { copied.value = false }, 2500)
}

const printSummary = () => {
  window.print()
}

const formattedDate = computed(() => recording.value ? moment(recording.value.created_at).format('MMMM D, YYYY') : '')
const formattedDuration = computed(() => {
  if (!recording.value || !recording.value.duration) return '00:00'
  const mins = Math.floor(recording.value.duration / 60)
  const secs = Math.floor(recording.value.duration % 60)
  return `${mins}:${secs.toString().padStart(2, '0')}`
})
</script>

<style scoped>
.shared-page-container {
  max-width: 900px;
  margin: 0 auto;
  padding: 3rem 2rem 5rem 2rem;
}

.shared-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  text-align: center;
  margin-bottom: 2.5rem;
}

.brand-row {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  background: var(--bg-secondary);
  border: 1px solid rgba(0, 0, 0, 0.08);
  padding: 0.35rem 0.85rem;
  border-radius: var(--radius-full);
  margin-bottom: 1.25rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.03);
}

.shared-logo-icon {
  width: 24px;
  height: 24px;
  border-radius: 6px;
  background: linear-gradient(135deg, #0071E3, #AF52DE);
  display: flex;
  align-items: center;
  justify-content: center;
}

.brand-title {
  font-size: 0.8rem;
  font-weight: 700;
  color: var(--text-primary);
  letter-spacing: -0.01em;
}

.page-title {
  font-size: 2.4rem;
  font-weight: 800;
  letter-spacing: -0.03em;
  color: var(--text-primary);
  margin-bottom: 1rem;
  line-height: 1.2;
}

.meta-pills-row {
  display: flex;
  align-items: center;
  gap: 0.65rem;
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
  justify-content: center;
}

.meta-pill {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  background: var(--bg-secondary);
  border: 1px solid rgba(0, 0, 0, 0.07);
  padding: 0.25rem 0.75rem;
  border-radius: var(--radius-full);
  font-size: 0.78rem;
  color: var(--text-secondary);
  font-weight: 500;
}

.medical-pill {
  background: rgba(16, 185, 129, 0.12);
  border-color: rgba(16, 185, 129, 0.3);
  color: #047857;
  font-weight: 600;
}

.pill-shared {
  background: var(--apple-blue-light);
  color: var(--apple-blue);
  font-weight: 600;
}

.shared-actions-bar {
  display: flex;
  align-items: center;
  gap: 0.65rem;
}

.apple-btn-secondary {
  display: inline-flex;
  align-items: center;
  gap: 0.45rem;
  background: var(--bg-secondary);
  border: 1px solid rgba(0, 0, 0, 0.1);
  padding: 0.55rem 1rem;
  border-radius: var(--radius-full);
  font-size: 0.84rem;
  font-weight: 600;
  color: var(--text-primary);
  cursor: pointer;
  transition: all 0.2s var(--apple-ease);
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.03);
}

.apple-btn-secondary:hover {
  background: rgba(0, 0, 0, 0.04);
  transform: translateY(-1px);
}

.apple-primary-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  background: var(--apple-blue);
  color: #FFFFFF;
  border: 1px solid rgba(255, 255, 255, 0.2);
  padding: 0.65rem 1.4rem;
  border-radius: var(--radius-full);
  font-size: 0.88rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s var(--apple-ease);
  box-shadow: 0 4px 12px rgba(0, 113, 227, 0.25);
}

.apple-primary-btn:hover {
  background: var(--apple-blue-hover);
  transform: translateY(-1px);
}

.shared-doc-wrapper {
  width: 100%;
}

.apple-doc-card {
  background: var(--white);
  border-radius: var(--radius-2xl);
  padding: 3.5rem 4rem;
  border: 1px solid rgba(0, 0, 0, 0.07);
  box-shadow: 0 8px 30px -4px rgba(0, 0, 0, 0.04), 0 1px 2px rgba(0, 0, 0, 0.02);
}

.doc-header {
  padding-bottom: 1.5rem;
  margin-bottom: 2rem;
  border-bottom: 1px solid rgba(0, 0, 0, 0.07);
}

.doc-icon-badge {
  width: 38px;
  height: 38px;
  border-radius: 10px;
  background: var(--apple-blue-light);
  display: flex;
  align-items: center;
  justify-content: center;
  margin-right: 0.5rem;
}

.medical-icon-badge {
  background: rgba(16, 185, 129, 0.12) !important;
}

.text-emerald-600 {
  color: #059669;
}

.doc-heading {
  font-size: 1.35rem;
  font-weight: 700;
  color: var(--text-primary);
  letter-spacing: -0.02em;
}

.doc-subheading {
  font-size: 0.82rem;
  color: var(--text-muted);
  display: block;
  margin-top: 0.15rem;
}

.empty-card {
  text-align: center;
  padding: 5rem 2rem;
  color: var(--text-muted);
}

.markdown-content {
  font-size: 1.05rem;
  line-height: 1.75;
  color: #1d1d1f;
}

.markdown-content :deep(h1) {
  font-size: 1.6rem;
  font-weight: 700;
  margin-top: 2rem;
  margin-bottom: 0.85rem;
}

.markdown-content :deep(h2) {
  font-size: 1.3rem;
  font-weight: 700;
  margin-top: 1.75rem;
  margin-bottom: 0.65rem;
}

.markdown-content :deep(h3) {
  font-size: 1.15rem;
  font-weight: 700;
  margin-top: 1.5rem;
  margin-bottom: 0.5rem;
}

.markdown-content :deep(p) {
  margin-bottom: 1.25rem;
  color: #333336;
}

.markdown-content :deep(ul), .markdown-content :deep(ol) {
  margin-bottom: 1.25rem;
  padding-left: 1.5rem;
}

.markdown-content :deep(li) {
  margin-bottom: 0.5rem;
  color: #333336;
}

.markdown-content :deep(strong) {
  color: #000000;
  font-weight: 600;
}

.markdown-content :deep(blockquote) {
  border-left: 3.5px solid var(--apple-blue);
  background: var(--neutral-50);
  padding: 0.85rem 1.25rem;
  margin: 1.5rem 0;
  border-radius: 0 var(--radius-md) var(--radius-md) 0;
  color: var(--text-secondary);
  font-style: italic;
}

.full-page-loader {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 80vh;
  gap: 1rem;
}

.loader-label {
  font-size: 0.95rem;
  color: var(--text-muted);
  font-weight: 500;
}

.text-blue { color: var(--apple-blue); }
.text-green { color: var(--apple-green); }
.font-tabular { font-variant-numeric: tabular-nums; }

@media (max-width: 768px) {
  .shared-page-container {
    padding: 1.5rem 1rem;
  }

  .page-title {
    font-size: 1.85rem;
  }

  .apple-doc-card {
    padding: 2rem 1.25rem;
  }
}
</style>
